---
- name: Create management user
  postgresql_user:
    name: postgres
    password: "{{ postgres_postgres_password }}"
    port: 6789
  become: true
  become_user: postgres

- name: Create db
  postgresql_db:
    name: "{{ postgres_test_db }}"
    port: 6789
  become: true
  become_user: postgres

- name: Create test user
  postgresql_user:
    name: "{{ postgres_test_username }}"
    password: "{{ postgres_test_user_password }}"
    port: 6789
  become: true
  become_user: postgres

- name: Add grants
  postgresql_privs:
    database: "{{ postgres_test_db }}"
    grant_option: yes
    privs: ALL
    type: database
    role: "{{ postgres_test_username }}"
    port: 6789
  become: true
  become_user: postgres
